---
title: "Demand Model"
author: ""
date: ""
output: html_document
---

```{r library setup, include=FALSE}
knitr::opts_chunk$set(message=FALSE, tidy=TRUE, tidy.opts=list(width.cutoff=60), echo=T)
  library(data.table)
  library(bit64)
  library(stringr)
  library(Rcpp)
  library(timeDate)
  library(chron)
  library(knitr)
  library(stringr)
  library(ggplot2)
  library(AER)
```

```{r define functions, echo=F}
# Functions
  plot_density = function(data, bins = 30, label, title, plot_mean = T){
     if (plot_mean){
         qplot(data, geom = 'blank') +   
         geom_line(aes(y = ..density.., colour = label), stat = 'density') +  
         geom_histogram(aes(y = ..density..), alpha = 0.5, bins = bins) +
         scale_colour_manual(name = 'Density', values = 'red') + 
         labs(title = title) +
         theme(legend.title = element_text(size=8),
               legend.text = element_text(size=8), legend.key = element_rect(size = 0.1)) +
         theme(plot.title = element_text(size=10, face = "bold", hjust=.5), 
               axis.title.x=element_blank(), axis.title.y=element_blank()) +
         geom_vline(xintercept = mean(data), colour="blue")+
         geom_text(aes(x=mean(data), y=.3, label=paste0("mean = ", round(mean(data),2))),
                   colour="blue", size=4)} 
     else{
         qplot(data, geom = 'blank') +   
         geom_line(aes(y = ..density.., colour = label), stat = 'density') +  
         geom_histogram(aes(y = ..density..), alpha = 0.5, bins = bins) +
         scale_colour_manual(name = 'Density', values = 'red') + 
         labs(title = title) +
         theme(legend.title = element_text(size=8),
               legend.text = element_text(size=8), legend.key = element_rect(size = 0.1)) +
         theme(plot.title = element_text(size=10, face = "bold", hjust=.5), 
               axis.title.x=element_blank(), axis.title.y=element_blank())}
   }
  
  doHistogram = function(dataset, timeperiod){
      for (i in resultBrand){
        data = dataset[brand_descr_corrected==i]
        for (j in variables){
          coefficients = data[, c(names(data)[str_sub(names(data),start=6)==j]), with=F]
          count = nrow(coefficients)
          # coefficient = coefficients[,1, with = F]
          coefficient_all = coefficients[,paste0("coef_", j),with=F]
          coefficient_all = coefficient_all[which(abs(coefficient_all) <=10),]
          plot_all = plot_density(coefficient_all[[1]], label = j, 
                                  title = paste0(timeperiod, ": ", i,
                                                 " (all, n=", count, ", nplot=", nrow(coefficient_all),")"))
          ggsave(paste0(timeperiod, "_", i, "_", j, "_all.png"), plot = plot_all, width = 5, height = 5)

          coefficients_sig = eval(parse(text = paste0("coefficients[pval_",j,"<0.05]")))
          count = nrow(coefficients_sig)
          if (count >0){
            coefficient_sig = coefficients_sig[,paste0("coef_", j),with=F]
            coefficient_sig = coefficient_sig[which(abs(coefficient_sig) <=10),]
            if (nrow(coefficient_sig) > 1){
              plot_sig = plot_density(coefficient_sig[[1]], label = j, 
                                      title = paste0(timeperiod, ": ", i,
                                                     " (sig, n=", count, ", nplot=", nrow(coefficient_sig),")"))
              ggsave(paste0(timeperiod, "_", i, "_", j, "_sig.png"), plot = plot_sig, width = 5, height = 5)
            }
          }
          # print(plot_all)
          # print(plot_sig)
        }
      }
  }
  
  cppFunction(
    'NumericVector stockdi(NumericVector x, double delta, double z) {
      int n = x.size();
      NumericVector y = clone(x);
      y[0] = z;
      for (int i = 1; i<n; i++){
      y[i] = (1-delta)*y[i-1] + delta*x[i-1];
      }
      return(y);
    }')
  
  myHoliday = function(inYear, holidayName, daysBefore, daysAfter){
              dates(as.character(seq((as.Date(holiday(inYear, holidayName))-daysBefore),
                                     as.Date(holiday(inYear, holidayName))-daysAfter ,by='day')),format="Y-M-D")
  }
```

##Step 1:
```{r directory and data, echo=F}
# Set directory and load the data
  dir_data = "~/PassThrough/Data/RMS-Build-2016/"
  module = 1393
  # module = 1340
  
# Load meta_data
  load(paste0(dir_data, "Meta-Data/Meta-Data-Corrected.RData"))
  meta_data = setDT(meta_data)[product_module_code==module, .(upc, upc_ver_uc_corrected, revenue_RMS, N_weeks_RMS)]
  meta_data = meta_data[, .(productRev = sum(revenue_RMS), productWeek = sum(N_weeks_RMS)),
                        by = c("upc", "upc_ver_uc_corrected")]
  setkey(meta_data, upc, upc_ver_uc_corrected)
  
# Load the product data, convert units to ounce  
  load(paste0(dir_data, "Meta-Data/Products-Corrected.RData"))
  product_data = setDT(products)[product_module_code==module]
  product_data[size1_units == "PO", `:=`(size1_amount = size1_amount*16, size1_units = "OZ" )]
  product_data = setDT(product_data)[size1_units=="OZ",.(upc, upc_ver_uc, upc_ver_uc_corrected, 
                                                         brand_descr_corrected, size1_amount, multi)]
  product_data = product_data[, .(brand_descr_corrected = brand_descr_corrected[1],
                                  size1_amount = size1_amount[1], multi=multi[1]),
                              by = c("upc", "upc_ver_uc_corrected")]
  
# Merge data; find the top brand
  setkey(product_data, upc, upc_ver_uc_corrected)
  product_data = meta_data[product_data]
  revenue = product_data[, .(brand_revenue = sum(productRev, na.rm=TRUE)), by = .(brand_descr_corrected)]
  top_brand = revenue[order(-brand_revenue), brand_descr_corrected][1:10]
  #save(top_brand, file="../../media/xlin0/share/xl150/top_brand_1393.RData")
```

```{r movement data}
# Movement data  
  all_move_file = list.files(paste0(dir_data, "RMS-Processed/Modules/", module))
  all_move = as.list(1:length(all_move_file))
  k = 0
  for (i in all_move_file){
    k = k+1
    load(paste0(dir_data, "RMS-Processed/Modules/", module, "/", i))
    move = move[!(is.na(base_price)|is.na(imputed_price))]
    move[, `:=`(store_rev = sum(units*imputed_price, na.rm=T)), by = .(upc, upc_ver_uc_corrected, store_code_uc)]
  
    setkey(product_data, upc, upc_ver_uc_corrected)
    setkey(move, upc, upc_ver_uc_corrected)
    # Half of the data is gone!
    move = move[product_data, nomatch=0L]
  
  # Obtain per unit price and units
    move[, `:=`(base_price = base_price/size1_amount, imputed_price = imputed_price/size1_amount,
                units = units*size1_amount*multi)]
    
  # Aggregate price to brand level (only consider top brands)
    move[!(brand_descr_corrected %in% top_brand), brand_descr_corrected := "OTHER"]

    all_move[[k]] = move[, .(base_cum= sum(store_rev*base_price, na.rm=T),
                    imputed_cum = sum(store_rev*imputed_price, na.rm=T),
                    wts_cum = sum(store_rev*(!is.na(imputed_price)), na.rm=T),
                    units = sum(units, na.rm=T)), 
                  by = .(brand_descr_corrected, store_code_uc, week_end)]
  }
  all_move = rbindlist(all_move)[, .(base_cum= sum(base_cum, na.rm=T),
                            imputed_cum = sum(imputed_cum, na.rm=T),
                            wts_cum = sum(wts_cum, na.rm=T),
                            units = sum(units, na.rm=T)), 
                        by = .(brand_descr_corrected, store_code_uc, week_end)]
  gc()
```

```{r store selection}
  # Aggregate to brand level

# Load the store data 
  load(paste0(dir_data, "Meta-Data/Stores.RData"))

  store_data = setDT(stores)[,.(store_code_uc, year, dma_code, dma_descr, parent_code)]
  # Use first dma for each store
  store_data[, `:=`(dma_code = dma_code[1], dma_descr = dma_descr[1]), by = c("store_code_uc")]
  store_data[, `:=`(nchain = length(unique(parent_code))), by = "store_code_uc"]
  store_data = store_data[nchain==1, ]
  store_data[, nchain:=NULL]
  # save(store_data, file="../../media/xlin0/share/xl150/store_data_1393.RData")  

# Extract year; Merge movement and store data
  all_move[, `:=`(year = as.integer(format(all_move$week_end, format = "%Y")))]
  setkeyv(all_move, c("store_code_uc", "year"))
  all_move = all_move[store_data, nomatch=0L]
  
# Compute the revenue for each store; share; culmulated share ranked by store revenues
  store_revenue = all_move[, .(revenue = sum(wts_cum, na.rm = T)), by = .(store_code_uc)]
  store_revenue[, share := revenue/sum(revenue, na.rm = T)]
  setorder(store_revenue, -share)
  store_revenue[, cumshare := cumsum(share)]
  store_revenue[, cumshare := cumshare-share]
  # save(store_revenue, file="../../media/xlin0/share/xl150/store_revenue_1393.RData")
  top_store = store_revenue[cumshare<=0.90, store_code_uc]  #### 80%?
  all_move = all_move[(store_code_uc %in% top_store),]
```  

```{r price indexes}    
# Calculate price indexes based on stores and dmas; 
  all_move[, `:=`(imputed_price = imputed_cum/wts_cum,
                  base_price = base_cum/wts_cum)]
  # How to generate outside price index?
  all_move[, `:=`(other_price = (sum(imputed_cum)-imputed_cum)/(sum(wts_cum)-wts_cum)),
           by = .(store_code_uc, week_end)]
  #drop the ones without other price index
  all_move = all_move[!is.na(other_price)]
```

```{r hasuman and macro}
# Calculate the Hausman IV
  dma_move = all_move[, .(dma_price = sum(imputed_cum)/sum(wts_cum)), 
                      by = .(brand_descr_corrected, dma_code, dma_descr, week_end)]
  dma_move[, nweek := .N, by = .(brand_descr_corrected, week_end)]
  dma_move[, hausman := (sum(dma_price) - dma_price) / (nweek-1), by = .(brand_descr_corrected, week_end)]
  dma_move[, `:=`(yearmonth = as.integer(format(dma_move$week_end, format = "%Y%m")))]
  
# Load the macroeconomics data; Merge with dma_move
  load("~/PassThrough/Data/Macro-Data/CPI-SA.RData")
  load("~/PassThrough/Data/Macro-Data/employment.RData")
  cpi[, yearmonth := as.integer(gsub("-","", year_month))]
  month_emply[, yearmonth := as.integer(gsub("-","", month))]
  macro_ind = month_emply[, .(yearmonth, dma_code, unemploy_rate)]
  setkey(cpi, yearmonth)
  setkey(macro_ind, yearmonth)
  macro_ind = macro_ind[cpi[, .(yearmonth, inflation=value)], nomatch=0L]
  setkey(dma_move, dma_code, yearmonth)
  setkey(macro_ind, dma_code, yearmonth)
  dma_move = dma_move[macro_ind, nomatch=0L]

# Merge movement and hausman, macro-economic data 
  dma_move[, `:=`(nweek=NULL, dma_descr=NULL)]
  setkey(all_move, brand_descr_corrected, dma_code, week_end)
  setkey(dma_move, brand_descr_corrected, dma_code, week_end)
  all_move = all_move[dma_move, nomatch=0L]
```

```{r variables}
# Decide if promotion exists --- two percent has observation of price higher than base price
# It seems that it happens more often than the original data.
  all_move[, `:=`(promotion = as.integer(imputed_price<=(0.95*base_price)))]

# Extract month; See if it's holiday
  all_move[, `:=`(Christmas=1*is.holiday(week_end, myHoliday(year,"USChristmasDay",7,0)),
                  Thanksgiving=1*is.holiday(week_end, myHoliday(year,"USThanksgivingDay",7,0)),
                  Easter=1*is.holiday(week_end, myHoliday(year,"Easter",7,0))), by = .(week_end, year)]
  
# Calculate reference price  
  delta = 0.1
  ref0 = 0.1
  
  setkey(all_move, store_code_uc, brand_descr_corrected, week_end)
  all_move[, `:=`(ref_price = shift(imputed_price)), by = .(brand_descr_corrected, store_code_uc)]
  # all_move[, `:=`(ref_price3 = stockdi(brand_idx_imputed, delta, ref0), 
  #                       ref_price4 = stockdi(category_idx_imputed, delta, ref0)), 
  #               by = .(store_code_uc, brand_descr_corrected)]
  
  # save(all_move, file="../../media/xlin0/share/xl150/move_1393.RData")
```

```{r log and IV}
### Here!!!!
# Take the log
# Add 1 to units
  all_move[, units := units + 1]
  all_move[, `:=`(lsold = log(units), lprice = log(imputed_price), lref = log(ref_price), 
                  lotherPrice = log(other_price), 
                  lhausman = log(hausman), lcpi = log(inflation), lunemploy = log(unemploy_rate))]
  
  all_move[, `:=`(labove_ref = lprice-lref, lbelow_ref = lprice-lref)]
  all_move[ref_price > imputed_price, labove_ref := 0]
  all_move[ref_price < imputed_price, lbelow_ref := 0]
  
# Calculate the IV1
  dma_move = all_move[, .(dma_above_ref = mean(labove_ref, na.rm = T), dma_below_ref = mean(lbelow_ref, na.rm = T)), 
                    by = .(brand_descr_corrected, dma_descr, week_end)]
  
  dma_move[, count_nonNA := .N - sum(is.na(dma_above_ref)), by = .(brand_descr_corrected, week_end)] 
  #dma_move[!is.na(dma_above_ref), count_nonNA := count_nonNA - 1]
  dma_move[, `:=`(IV1_above_ref = mean(dma_above_ref, na.rm = T), IV1_below_ref = mean(dma_below_ref, na.rm = T)), 
             by = .(brand_descr_corrected, week_end)]
  dma_move[!is.na(dma_above_ref),
             `:=`(IV1_above_ref = (sum(dma_above_ref, na.rm = T) - dma_above_ref) / (count_nonNA - 1),
                  IV1_below_ref = (sum(dma_below_ref, na.rm = T) - dma_below_ref) / (count_nonNA - 1)),
            by = .(brand_descr_corrected, week_end)]
  dma_move[count_nonNA == 0 | (count_nonNA == 1 & !is.na(dma_above_ref)), `:=`(IV1_above_ref = NA, IV1_below_ref = NA)]
  
  all_move = merge(all_move, dma_move[, .(brand_descr_corrected, dma_descr, week_end, IV1_above_ref, IV1_below_ref)], 
                 by = c("brand_descr_corrected", "dma_descr", "week_end"))
  
# Calculate the IV2
  all_move[, `:=`(IV2_above_ref = lhausman-lref, IV2_below_ref = lhausman-lref)]
  all_move[ref_price > imputed_price, IV2_above_ref := 0]
  all_move[ref_price < imputed_price, IV2_below_ref := 0]  

  # save(all_move, file="../../media/xlin0/share/xl150/move3_1393.RData")
```

```{r data selection}
# Keep only the store & brand that has (valid) observations more than 104 weeks (2yrs) in the regression
  all_move[, `:=`(count = sum(rowSums(is.na(.SD)) == 0)), by = .(store_code_uc, brand_descr_corrected)]
  all_move = all_move[count >= 104]  
  
  all_move[, `:=`(count_p1 = sum(rowSums(is.na(.SD)) == 0 & year %in% 2006:2007),
                     count_p2 = sum(rowSums(is.na(.SD)) == 0 & yearmonth %in% 200806:201012),
                     count_p3 = sum(rowSums(is.na(.SD)) == 0 & year %in% 2008)), 
              by = .(store_code_uc, brand_descr_corrected)]
  all_move = all_move[count_p1 >= 15 & count_p2 >= 15 & count_p3 >= 10]  
  
  target_data = all_move[brand_descr_corrected %in% top_brand[1:5]]
```

```{r regression}
# 1 Non-aggregated
# 1.1 IV1
  reg_data = target_data[,.(year, yearmonth, week_end, lsold, lprice, 
                           lref, labove_ref, lbelow_ref, IV1_above_ref, IV1_below_ref, lotherPrice, 
                           Christmas, Thanksgiving, Easter, promotion, brand_descr_corrected, store_code_uc, 
                           lhausman, lcpi, lunemploy)]

  result_all = reg_data[, .(model = list(ivreg(lsold ~ lprice + labove_ref + lbelow_ref + lotherPrice + 
                                               lcpi + lunemploy + Christmas + Thanksgiving + Easter + 
                                               promotion | lhausman + IV1_above_ref + IV1_below_ref + lotherPrice + 
                                               lcpi + lunemploy + Christmas + Thanksgiving + Easter + promotion,
                                             na.action = na.exclude))),
                        by = .(store_code_uc, brand_descr_corrected)]

  result_0607 = reg_data[year %in% 2006:2007, 
                         .(model = list(ivreg(lsold ~ lprice + labove_ref + lbelow_ref + lotherPrice + 
                                               lcpi + lunemploy + Christmas + Thanksgiving + Easter + 
                                               promotion | lhausman + IV1_above_ref + IV1_below_ref + lotherPrice + 
                                               lcpi + lunemploy + Christmas + Thanksgiving + Easter + promotion,
                                             na.action = na.exclude))),
                        by = .(store_code_uc, brand_descr_corrected)]
  result_0810 = reg_data[yearmonth %in% 200806:201012, 
                         .(model = list(ivreg(lsold ~ lprice + labove_ref + lbelow_ref + lotherPrice + 
                                               lcpi + lunemploy + Christmas + Thanksgiving + Easter + 
                                               promotion | lhausman + IV1_above_ref + IV1_below_ref + lotherPrice + 
                                               lcpi + lunemploy + Christmas + Thanksgiving + Easter + promotion,
                                             na.action = na.exclude))),
                        by = .(store_code_uc, brand_descr_corrected)]  
  result_08 = reg_data[year %in% 2008, 
                         .(model = list(ivreg(lsold ~ lprice + labove_ref + lbelow_ref + lotherPrice + 
                                               lcpi + lunemploy + Christmas + Thanksgiving + Easter + 
                                               promotion | lhausman + IV1_above_ref + IV1_below_ref + lotherPrice + 
                                               lcpi + lunemploy + Christmas + Thanksgiving + Easter + promotion,
                                             na.action = na.exclude))),
                        by = .(store_code_uc, brand_descr_corrected)]
  
# coefficients and p-values
  result_all[, c("intercept", "coef_lprice", "coef_labove_ref", "coef_lbelow_ref", "coef_lotherPrice", 
               "coef_lcpi", "coef_lunemploy", "coef_Christmas", "coef_Thanksgiving", "coef_Easter", 
               "coef_promotion") := as.list(model[[1]]$coefficients),
             by = .(store_code_uc, brand_descr_corrected)]  
  result_all = na.omit(result_all)
  result_all[, c("pval_intercept", "pval_lprice", "pval_labove_ref", "pval_lbelow_ref", "pval_lotherPrice",
               "pval_lcpi", "pval_lunemploy", "pval_Christmas", "pval_Thanksgiving", "pval_Easter",
               "pval_promotion") := as.list(summary(model[[1]])$coefficients[,"Pr(>|t|)"]),
             by = .(store_code_uc, brand_descr_corrected)]
  
  result_0607[, c("intercept", "coef_lprice", "coef_labove_ref", "coef_lbelow_ref", "coef_lotherPrice", 
               "coef_lcpi", "coef_lunemploy", "coef_Christmas", "coef_Thanksgiving", "coef_Easter", 
               "coef_promotion") := as.list(model[[1]]$coefficients),
             by = .(store_code_uc, brand_descr_corrected)]
  result_0607 = na.omit(result_0607)
  result_0607[, c("pval_intercept", "pval_lprice", "pval_labove_ref", "pval_lbelow_ref", "pval_lotherPrice",
               "pval_lcpi", "pval_lunemploy", "pval_Christmas", "pval_Thanksgiving", "pval_Easter",
               "pval_promotion") := as.list(summary(model[[1]])$coefficients[,"Pr(>|t|)"]),
             by = .(store_code_uc, brand_descr_corrected)]
  
  result_0810[, c("intercept", "coef_lprice", "coef_labove_ref", "coef_lbelow_ref", "coef_lotherPrice", 
               "coef_lcpi", "coef_lunemploy", "coef_Christmas", "coef_Thanksgiving", "coef_Easter", 
               "coef_promotion") := as.list(model[[1]]$coefficients),
             by = .(store_code_uc, brand_descr_corrected)]
  result_0810 = na.omit(result_0810)
  result_0810[, c("pval_intercept", "pval_lprice", "pval_labove_ref", "pval_lbelow_ref", "pval_lotherPrice",
               "pval_lcpi", "pval_lunemploy", "pval_Christmas", "pval_Thanksgiving", "pval_Easter",
               "pval_promotion") := as.list(summary(model[[1]])$coefficients[,"Pr(>|t|)"]),
             by = .(store_code_uc, brand_descr_corrected)]
  
  result_08[, c("intercept", "coef_lprice", "coef_labove_ref", "coef_lbelow_ref", "coef_lotherPrice", 
               "coef_lcpi", "coef_lunemploy", "coef_Christmas", "coef_Thanksgiving", "coef_Easter", 
               "coef_promotion") := as.list(model[[1]]$coefficients),
             by = .(store_code_uc, brand_descr_corrected)]
  result_08 = na.omit(result_08)
  result_08[, c("pval_intercept", "pval_lprice", "pval_labove_ref", "pval_lbelow_ref", "pval_lotherPrice",
               "pval_lcpi", "pval_lunemploy", "pval_Christmas", "pval_Thanksgiving", "pval_Easter",
               "pval_promotion") := as.list(summary(model[[1]])$coefficients[,"Pr(>|t|)"]),
             by = .(store_code_uc, brand_descr_corrected)]
   
# Histograms    
  variables = c("lprice", "labove_ref", "lbelow_ref", "lotherPrice", "lcpi", "lunemploy", 
                "Christmas", "Thanksgiving", "Easter", "promotion")
  resultBrand = unique(result_all$brand_descr_corrected)
  
  #doHistogram(result_all, "All time")
  #doHistogram(result_0607, "2006.01-2007.12")
  #doHistogram(result_0810, "2008.06-2010.12")
  #doHistogram(result_08, "2008")
```

```{r}
# 1.2 IV2
  reg_data = target_data[, .(year, yearmonth, week_end, lsold, lprice, 
                             lref, labove_ref, lbelow_ref, IV2_above_ref, IV2_below_ref, lotherPrice, 
                             Christmas, Thanksgiving, Easter, promotion, brand_descr_corrected, store_code_uc, 
                             lhausman, lcpi, lunemploy)]

  result_all = reg_data[, .(model = list(ivreg(lsold ~ lprice + labove_ref + lbelow_ref + lotherPrice + 
                                        lcpi + lunemploy + Christmas + Thanksgiving + Easter + 
                                        promotion | lhausman + IV2_above_ref + IV2_below_ref + lotherPrice + 
                                        lcpi + lunemploy + Christmas + Thanksgiving + Easter + promotion,
                                        na.action = na.exclude))),
                        by = .(store_code_uc, brand_descr_corrected)]
  result_0607 = reg_data[year %in% 2006:2007, 
                         .(model = list(ivreg(lsold ~ lprice + labove_ref + lbelow_ref + lotherPrice + 
                                        lcpi + lunemploy + Christmas + Thanksgiving + Easter + 
                                        promotion | lhausman + IV2_above_ref + IV2_below_ref + lotherPrice + 
                                        lcpi + lunemploy + Christmas + Thanksgiving + Easter + promotion,
                                        na.action = na.exclude))),
                        by = .(store_code_uc, brand_descr_corrected)]
  result_0810 = reg_data[yearmonth %in% 200806:201012, 
                         .(model = list(ivreg(lsold ~ lprice + labove_ref + lbelow_ref + lotherPrice + 
                                        lcpi + lunemploy + Christmas + Thanksgiving + Easter + 
                                        promotion | lhausman + IV2_above_ref + IV2_below_ref + lotherPrice + 
                                        lcpi + lunemploy + Christmas + Thanksgiving + Easter + promotion,
                                        na.action = na.exclude))),
                        by = .(store_code_uc, brand_descr_corrected)]  
  result_08 = reg_data[year %in% 2008, 
                         .(model = list(ivreg(lsold ~ lprice + labove_ref + lbelow_ref + lotherPrice + 
                                        lcpi + lunemploy + Christmas + Thanksgiving + Easter + 
                                        promotion | lhausman + IV2_above_ref + IV2_below_ref + lotherPrice + 
                                        lcpi + lunemploy + Christmas + Thanksgiving + Easter + promotion,
                                        na.action = na.exclude))),
                        by = .(store_code_uc, brand_descr_corrected)]
  
# coefficients and p-values
  result_all[, c("intercept", "coef_lprice", "coef_labove_ref", "coef_lbelow_ref", "coef_lotherPrice", 
               "coef_lcpi", "coef_lunemploy", "coef_Christmas", "coef_Thanksgiving", "coef_Easter", 
               "coef_promotion") := as.list(model[[1]]$coefficients),
             by = .(store_code_uc, brand_descr_corrected)]  
  result_all = na.omit(result_all)
  result_all[, c("pval_intercept", "pval_lprice", "pval_labove_ref", "pval_lbelow_ref", "pval_lotherPrice",
               "pval_lcpi", "pval_lunemploy", "pval_Christmas", "pval_Thanksgiving", "pval_Easter",
               "pval_promotion") := as.list(summary(model[[1]])$coefficients[,"Pr(>|t|)"]),
             by = .(store_code_uc, brand_descr_corrected)]
  
  result_0607[, c("intercept", "coef_lprice", "coef_labove_ref", "coef_lbelow_ref", "coef_lotherPrice", 
               "coef_lcpi", "coef_lunemploy", "coef_Christmas", "coef_Thanksgiving", "coef_Easter", 
               "coef_promotion") := as.list(model[[1]]$coefficients),
             by = .(store_code_uc, brand_descr_corrected)]
  result_0607 = na.omit(result_0607)
  result_0607[, c("pval_intercept", "pval_lprice", "pval_labove_ref", "pval_lbelow_ref", "pval_lotherPrice",
               "pval_lcpi", "pval_lunemploy", "pval_Christmas", "pval_Thanksgiving", "pval_Easter",
               "pval_promotion") := as.list(summary(model[[1]])$coefficients[,"Pr(>|t|)"]),
             by = .(store_code_uc, brand_descr_corrected)]
  
  result_0810[, c("intercept", "coef_lprice", "coef_labove_ref", "coef_lbelow_ref", "coef_lotherPrice", 
               "coef_lcpi", "coef_lunemploy", "coef_Christmas", "coef_Thanksgiving", "coef_Easter", 
               "coef_promotion") := as.list(model[[1]]$coefficients),
             by = .(store_code_uc, brand_descr_corrected)]
  result_0810 = na.omit(result_0810)
  result_0810[, c("pval_intercept", "pval_lprice", "pval_labove_ref", "pval_lbelow_ref", "pval_lotherPrice",
               "pval_lcpi", "pval_lunemploy", "pval_Christmas", "pval_Thanksgiving", "pval_Easter",
               "pval_promotion") := as.list(summary(model[[1]])$coefficients[,"Pr(>|t|)"]),
             by = .(store_code_uc, brand_descr_corrected)]
  
  result_08[, c("intercept", "coef_lprice", "coef_labove_ref", "coef_lbelow_ref", "coef_lotherPrice", 
               "coef_lcpi", "coef_lunemploy", "coef_Christmas", "coef_Thanksgiving", "coef_Easter", 
               "coef_promotion") := as.list(model[[1]]$coefficients),
             by = .(store_code_uc, brand_descr_corrected)]
  result_08 = na.omit(result_08)
  result_08[, c("pval_intercept", "pval_lprice", "pval_labove_ref", "pval_lbelow_ref", "pval_lotherPrice",
               "pval_lcpi", "pval_lunemploy", "pval_Christmas", "pval_Thanksgiving", "pval_Easter",
               "pval_promotion") := as.list(summary(model[[1]])$coefficients[,"Pr(>|t|)"]),
             by = .(store_code_uc, brand_descr_corrected)]
  
# Histograms    
  variables = c("lprice", "labove_ref", "lbelow_ref", "lotherPrice", "lcpi", "lunemploy", 
                "Christmas", "Thanksgiving", "Easter", "promotion")  
  resultBrand = unique(result_all$brand_descr_corrected)
  
  #doHistogram(result_all, "All time")
  #doHistogram(result_0607, "2006.01-2007.12")
  #doHistogram(result_0810, "2008.06-2010.12")
  #doHistogram(result_08, "2008")
```

```{r}
# 1.3 IV3
  reg_data = target_data[, .(year, yearmonth, week_end, lsold, lprice, lref, labove_ref, lbelow_ref,
                           lotherPrice, Christmas, Thanksgiving, Easter, promotion, 
                           brand_descr_corrected, store_code_uc, lhausman, lunemploy, lcpi)]

  result_all = reg_data
  result_all[, lprice_fitted := fitted(lm(lprice ~ lhausman + lref + lotherPrice + lcpi + lunemploy + 
                                           Christmas + Thanksgiving + Easter + promotion, na.action = na.exclude)), 
               by = .(store_code_uc, brand_descr_corrected)]

  result_all[, `:=`(labove_ref2 = lprice_fitted-lref, lbelow_ref2 = lprice_fitted-lref)]
  result_all[lref > lprice_fitted, labove_ref2 := 0]
  result_all[lref < lprice_fitted, lbelow_ref2 := 0]
  
  result_all = result_all[, .(model = list(lm(lsold ~ lprice_fitted + labove_ref2 + lbelow_ref2 + lotherPrice + 
                                               lcpi + lunemploy + Christmas + Thanksgiving + Easter + 
                                               promotion, na.action = na.exclude))),
                        by = .(store_code_uc, brand_descr_corrected)]
  
  
  result_0607 = reg_data[year %in% 2006:2007, ]
  result_0607[, lprice_fitted := fitted(lm(lprice ~ lhausman + lref + lotherPrice + lcpi + lunemploy + 
                                           Christmas + Thanksgiving + Easter + promotion, na.action = na.exclude)), 
               by = .(store_code_uc, brand_descr_corrected)]
  
  result_0607[, `:=`(labove_ref2 = lprice_fitted-lref, lbelow_ref2 = lprice_fitted-lref)]
  result_0607[lref > lprice_fitted, labove_ref2 := 0]
  result_0607[lref < lprice_fitted, lbelow_ref2 := 0]

  result_0607 = result_0607[, .(model = list(lm(lsold ~ lprice_fitted + labove_ref2 + lbelow_ref2 + lotherPrice + 
                                               lcpi + lunemploy + Christmas + Thanksgiving + Easter + 
                                               promotion, na.action = na.exclude))),
                            by = .(store_code_uc, brand_descr_corrected)]
  
  result_0810 = reg_data[yearmonth %in% 200806:201012, ]
  result_0810[, lprice_fitted := fitted(lm(lprice ~ lhausman + lref + lotherPrice + lcpi + lunemploy + 
                                           Christmas + Thanksgiving + Easter + promotion, na.action = na.exclude)), 
               by = .(store_code_uc, brand_descr_corrected)]
  
  result_0810[, `:=`(labove_ref2 = lprice_fitted-lref, lbelow_ref2 = lprice_fitted-lref)]
  result_0810[lref > lprice_fitted, labove_ref2 := 0]
  result_0810[lref < lprice_fitted, lbelow_ref2 := 0]

  result_0810 = result_0810[, .(model = list(lm(lsold ~ lprice_fitted + labove_ref2 + lbelow_ref2 + lotherPrice + 
                                               lcpi + lunemploy + Christmas + Thanksgiving + Easter + 
                                               promotion, na.action = na.exclude))),
                            by = .(store_code_uc, brand_descr_corrected)]
  
  result_08 = reg_data[year %in% 2008, ]
  result_08[, lprice_fitted := fitted(lm(lprice ~ lhausman + lref + lotherPrice + lcpi + lunemploy + 
                                           Christmas + Thanksgiving + Easter + promotion, na.action = na.exclude)), 
               by = .(store_code_uc, brand_descr_corrected)]
  
  result_08[, `:=`(labove_ref2 = lprice_fitted-lref, lbelow_ref2 = lprice_fitted-lref)]
  result_08[lref > lprice_fitted, labove_ref2 := 0]
  result_08[lref < lprice_fitted, lbelow_ref2 := 0]

  result_08 = result_08[, .(model = list(lm(lsold ~ lprice_fitted + labove_ref2 + lbelow_ref2 + lotherPrice + 
                                               lcpi + lunemploy + Christmas + Thanksgiving + Easter + 
                                               promotion, na.action = na.exclude))),
                            by = .(store_code_uc, brand_descr_corrected)]
  
  # coefficients and p-values
  result_all[, c("intercept", "coef_lprice_fitted", "coef_labove_ref2", "coef_lbelow_ref2", "coef_lotherPrice", 
               "coef_lcpi", "coef_lunemploy", "coef_Christmas", "coef_Thanksgiving", "coef_Easter", 
               "coef_promotion") := unlist(model)[which(grepl("coefficient",names(unlist(model))))],
             by = .(store_code_uc, brand_descr_corrected)]  
  result_all = na.omit(result_all)
  result_all[, c("pval_intercept", "pval_lprice_fitted", "pval_labove_ref2", "pval_lbelow_ref2", "pval_lotherPrice",
               "pval_lcpi", "pval_lunemploy", "pval_Christmas", "pval_Thanksgiving", "pval_Easter",
               "pval_promotion") := as.list(summary(model[[1]])$coefficients[,"Pr(>|t|)"]),
             by = .(store_code_uc, brand_descr_corrected)]
  
  result_0607[, c("intercept", "coef_lprice_fitted", "coef_labove_ref2", "coef_lbelow_ref2", "coef_lotherPrice", 
               "coef_lcpi", "coef_lunemploy", "coef_Christmas", "coef_Thanksgiving", "coef_Easter", 
               "coef_promotion") := unlist(model)[which(grepl("coefficient",names(unlist(model))))],
             by = .(store_code_uc, brand_descr_corrected)]
  result_0607 = na.omit(result_0607)
  result_0607[, c("pval_intercept", "pval_lprice_fitted", "pval_labove_ref2", "pval_lbelow_ref2", "pval_lotherPrice",
               "pval_lcpi", "pval_lunemploy", "pval_Christmas", "pval_Thanksgiving", "pval_Easter",
               "pval_promotion") := as.list(summary(model[[1]])$coefficients[,"Pr(>|t|)"]),
             by = .(store_code_uc, brand_descr_corrected)]
  
  result_0810[, c("intercept", "coef_lprice_fitted", "coef_labove_ref2", "coef_lbelow_ref2", "coef_lotherPrice", 
               "coef_lcpi", "coef_lunemploy", "coef_Christmas", "coef_Thanksgiving", "coef_Easter", 
               "coef_promotion") := unlist(model)[which(grepl("coefficient",names(unlist(model))))],
             by = .(store_code_uc, brand_descr_corrected)]
  result_0810 = na.omit(result_0810)
  result_0810[, c("pval_intercept", "pval_lprice_fitted", "pval_labove_ref2", "pval_lbelow_ref2", "pval_lotherPrice",
               "pval_lcpi", "pval_lunemploy", "pval_Christmas", "pval_Thanksgiving", "pval_Easter",
               "pval_promotion") := as.list(summary(model[[1]])$coefficients[,"Pr(>|t|)"]),
             by = .(store_code_uc, brand_descr_corrected)]
  
  result_08[, c("intercept", "coef_lprice_fitted", "coef_labove_ref2", "coef_lbelow_ref2", "coef_lotherPrice", 
               "coef_lcpi", "coef_lunemploy", "coef_Christmas", "coef_Thanksgiving", "coef_Easter", 
               "coef_promotion") := unlist(model)[which(grepl("coefficient",names(unlist(model))))],
             by = .(store_code_uc, brand_descr_corrected)]
  result_08 = na.omit(result_08)
  result_08[, c("pval_intercept", "pval_lprice_fitted", "pval_labove_ref2", "pval_lbelow_ref2", "pval_lotherPrice",
               "pval_lcpi", "pval_lunemploy", "pval_Christmas", "pval_Thanksgiving", "pval_Easter",
               "pval_promotion") := as.list(summary(model[[1]])$coefficients[,"Pr(>|t|)"]),
             by = .(store_code_uc, brand_descr_corrected)]
   
# Histograms    
  variables = c("lprice_fitted", "labove_ref2", "lbelow_ref2", "lotherPrice", "lcpi", "lunemploy", 
                "Christmas", "Thanksgiving", "Easter", "promotion")
  resultBrand = unique(result_all$brand_descr_corrected)
  
  doHistogram(result_all, "All time")
  doHistogram(result_0607, "2006.01-2007.12")
  doHistogram(result_0810, "2008.06-2010.12")
  doHistogram(result_08, "2008")
```


```{r aggregate}
# 2 aggregated to chain-market level;
  load(paste0(dir_data, "Meta-Data/store_meta.RData"))
  all_move = merge(all_move, RMS_store[,.(store_code_uc, year, revenue)], by = c("store_code_uc", "year"))

  all_move = all_move[,.(brand_idx_imputed = mean(brand_idx_imputed, na.rm=T), 
                         units = sum(units, na.rm=T), units2 = sum(units*revenue, na.rm = T)/sum(revenue, na.rm = T),
                         promotion = mean(promotion, na.rm = T), 
                         imputed_cum = sum(imputed_cum, na.rm=T), wts_cum = sum(wts_cum, na.rm=T)), 
                  by = .(dma_descr, chain_mkt, brand_descr_corrected, year, yearmonth, week_end, 
                               hausman, unemploy_rate, cpi)]
  all_move[, `:=`(allOther_idx_imputed = (sum(imputed_cum)-imputed_cum)/(sum(wts_cum)-wts_cum)),
                 by = .(chain_mkt, week_end)]
  
# To see if it's holiday
  all_move[, `:=`(Christmas=1*is.holiday(week_end, myHoliday(year,"USChristmasDay",7,0)),
                  Thanksgiving=1*is.holiday(week_end, myHoliday(year,"USThanksgivingDay",7,0)),
                  Easter=1*is.holiday(week_end, myHoliday(year,"Easter",7,0))), by = .(week_end, year)]
  
# Calculate reference price  
  setkey(all_move, week_end)
  all_move[, `:=`(ref_price = shift(brand_idx_imputed)), by = .(chain_mkt, brand_descr_corrected)]
  
# Take log
  all_move[units==0, units := 1]
  all_move[units2==0, units2 := 1]
  all_move[, `:=`(lsold = log(units), lsold2 = log(units2), lprice = log(brand_idx_imputed), lref = log(ref_price),
                  lotherPrice = log(allOther_idx_imputed), 
                  lhausman = log(hausman), lcpi = log(cpi), lunemploy = log(unemploy_rate))]
  
  all_move[, `:=`(labove_ref = lprice-lref, lbelow_ref = lprice-lref)]
  all_move[ref_price > brand_idx_imputed, labove_ref := 0]
  all_move[ref_price < brand_idx_imputed, lbelow_ref := 0]

  
 # Calculate the IV1
  dma_move = all_move[, .(dma_above_ref = mean(labove_ref, na.rm = T), dma_below_ref = mean(lbelow_ref, na.rm = T)), 
                    by = .(brand_descr_corrected, dma_descr, week_end)]
  
  dma_move[, count_nonNA := .N - sum(is.na(dma_above_ref)), by = .(brand_descr_corrected, week_end)] 
  dma_move[, `:=`(IV1_above_ref = mean(dma_above_ref, na.rm = T), IV1_below_ref = mean(dma_below_ref, na.rm = T)), 
             by = .(brand_descr_corrected, week_end)]
  dma_move[!is.na(dma_above_ref),
             `:=`(IV1_above_ref = (sum(dma_above_ref, na.rm = T) - dma_above_ref) / (count_nonNA - 1),
                  IV1_below_ref = (sum(dma_below_ref, na.rm = T) - dma_below_ref) / (count_nonNA - 1)),
            by = .(brand_descr_corrected, week_end)]
  dma_move[count_nonNA == 0 | (count_nonNA == 1 & !is.na(dma_above_ref)), `:=`(IV1_above_ref = NA, IV1_below_ref = NA)]
  
  all_move = merge(all_move, dma_move[, .(brand_descr_corrected, dma_descr, week_end, IV1_above_ref, IV1_below_ref)], 
                 by = c("brand_descr_corrected", "dma_descr", "week_end"))

# Calculate the IV2
  all_move[, `:=`(IV2_above_ref = lhausman-lref, IV2_below_ref = lhausman-lref)]
  all_move[ref_price > brand_idx_imputed, IV2_above_ref := 0]
  all_move[ref_price < brand_idx_imputed, IV2_below_ref := 0]  
```

```{r top chain-markets}
# Throw the chain_mkt with less than 3 stores
  chain_mkt_count = store_data[store_code_uc %in% top_store,
                               .(count_store = length(unique(store_code_uc))), by = .(chain_mkt)]
  top_chain = chain_mkt_count[(count_store >= 3), chain_mkt]  
  
  target_data = all_move[brand_descr_corrected %in% top_brand[1:5] & chain_mkt %in% top_chain]
```    

```{r regression}
# 2.1 IV1
  reg_data = target_data[, .(year, yearmonth, week_end, lsold, lprice, 
                             lref, labove_ref, lbelow_ref, IV1_above_ref, IV1_below_ref, lotherPrice, 
                             Christmas, Thanksgiving, Easter, promotion, brand_descr_corrected, chain_mkt, 
                             lhausman, lunemploy, lcpi)]

  result_all = reg_data[, .(model = list(ivreg(lsold ~ lprice + labove_ref + lbelow_ref + lotherPrice + 
                                               lcpi + lunemploy + Christmas + Thanksgiving + Easter + 
                                               promotion | lhausman + IV1_above_ref + IV1_below_ref + lotherPrice + 
                                               lcpi + lunemploy + Christmas + Thanksgiving + Easter + promotion,
                                             na.action = na.exclude))),
                        by = .(chain_mkt, brand_descr_corrected)]
  result_0607 = reg_data[year %in% 2006:2007, 
                         .(model = list(ivreg(lsold ~ lprice + labove_ref + lbelow_ref + lotherPrice + 
                                               lcpi + lunemploy + Christmas + Thanksgiving + Easter + 
                                               promotion | lhausman + IV1_above_ref + IV1_below_ref + lotherPrice + 
                                               lcpi + lunemploy + Christmas + Thanksgiving + Easter + promotion,
                                             na.action = na.exclude))),
                        by = .(chain_mkt, brand_descr_corrected)]
  result_0810 = reg_data[yearmonth %in% 200806:201012, 
                         .(model = list(ivreg(lsold ~ lprice + labove_ref + lbelow_ref + lotherPrice + 
                                               lcpi + lunemploy + Christmas + Thanksgiving + Easter + 
                                               promotion | lhausman + IV1_above_ref + IV1_below_ref + lotherPrice + 
                                               lcpi + lunemploy + Christmas + Thanksgiving + Easter + promotion,
                                             na.action = na.exclude))),
                        by = .(chain_mkt, brand_descr_corrected)]  
  result_08 = reg_data[year %in% 2008, 
                         .(model = list(ivreg(lsold ~ lprice + labove_ref + lbelow_ref + lotherPrice + 
                                               lcpi + lunemploy + Christmas + Thanksgiving + Easter + 
                                               promotion | lhausman + IV1_above_ref + IV1_below_ref + lotherPrice + 
                                               lcpi + lunemploy + Christmas + Thanksgiving + Easter + promotion,
                                             na.action = na.exclude))),
                        by = .(chain_mkt, brand_descr_corrected)]
  
# coefficients and p-values
  result_all[, c("intercept", "coef_lprice", "coef_labove_ref", "coef_lbelow_ref", "coef_lotherPrice", 
               "coef_lcpi", "coef_lunemploy", "coef_Christmas", "coef_Thanksgiving", "coef_Easter", 
               "coef_promotion") := as.list(model[[1]]$coefficients),
             by = .(chain_mkt, brand_descr_corrected)]  
  result_all = na.omit(result_all)
  result_all[, c("pval_intercept", "pval_lprice", "pval_labove_ref", "pval_lbelow_ref", "pval_lotherPrice",
               "pval_lcpi", "pval_lunemploy", "pval_Christmas", "pval_Thanksgiving", "pval_Easter",
               "pval_promotion") := as.list(summary(model[[1]])$coefficients[,"Pr(>|t|)"]),
             by = .(chain_mkt, brand_descr_corrected)]
  
  result_0607[, c("intercept", "coef_lprice", "coef_labove_ref", "coef_lbelow_ref", "coef_lotherPrice", 
               "coef_lcpi", "coef_lunemploy", "coef_Christmas", "coef_Thanksgiving", "coef_Easter", 
               "coef_promotion") := as.list(model[[1]]$coefficients),
             by = .(chain_mkt, brand_descr_corrected)]
  result_0607 = na.omit(result_0607)
  result_0607[, c("pval_intercept", "pval_lprice", "pval_labove_ref", "pval_lbelow_ref", "pval_lotherPrice",
               "pval_lcpi", "pval_lunemploy", "pval_Christmas", "pval_Thanksgiving", "pval_Easter",
               "pval_promotion") := as.list(summary(model[[1]])$coefficients[,"Pr(>|t|)"]),
             by = .(chain_mkt, brand_descr_corrected)]
  
  result_0810[, c("intercept", "coef_lprice", "coef_labove_ref", "coef_lbelow_ref", "coef_lotherPrice", 
               "coef_lcpi", "coef_lunemploy", "coef_Christmas", "coef_Thanksgiving", "coef_Easter", 
               "coef_promotion") := as.list(model[[1]]$coefficients),
             by = .(chain_mkt, brand_descr_corrected)]
  result_0810 = na.omit(result_0810)
  result_0810[, c("pval_intercept", "pval_lprice", "pval_labove_ref", "pval_lbelow_ref", "pval_lotherPrice",
               "pval_lcpi", "pval_lunemploy", "pval_Christmas", "pval_Thanksgiving", "pval_Easter",
               "pval_promotion") := as.list(summary(model[[1]])$coefficients[,"Pr(>|t|)"]),
             by = .(chain_mkt, brand_descr_corrected)]
  
  result_08[, c("intercept", "coef_lprice", "coef_labove_ref", "coef_lbelow_ref", "coef_lotherPrice", 
               "coef_lcpi", "coef_lunemploy", "coef_Christmas", "coef_Thanksgiving", "coef_Easter", 
               "coef_promotion") := as.list(model[[1]]$coefficients),
             by = .(chain_mkt, brand_descr_corrected)]
  result_08 = na.omit(result_08)
  result_08[, c("pval_intercept", "pval_lprice", "pval_labove_ref", "pval_lbelow_ref", "pval_lotherPrice",
               "pval_lcpi", "pval_lunemploy", "pval_Christmas", "pval_Thanksgiving", "pval_Easter",
               "pval_promotion") := as.list(summary(model[[1]])$coefficients[,"Pr(>|t|)"]),
             by = .(chain_mkt, brand_descr_corrected)]
   
# Histograms    
  variables = c("lprice", "labove_ref", "lbelow_ref", "lotherPrice", "lcpi", "lunemploy", 
                "Christmas", "Thanksgiving", "Easter", "promotion")
  resultBrand = unique(result_all$brand_descr_corrected)
  
  doHistogram(result_all, "All time")
  doHistogram(result_0607, "2006.01-2007.12")
  doHistogram(result_0810, "2008.06-2010.12")
  doHistogram(result_08, "2008")
```

```{r}
# 2.2 IV2
  reg_data = target_data[, .(year, yearmonth, week_end, lsold, lprice, 
                             lref, labove_ref, lbelow_ref, IV2_above_ref, IV2_below_ref, lotherPrice, 
                             Christmas, Thanksgiving, Easter, promotion, brand_descr_corrected, chain_mkt, 
                             lhausman, lunemploy, lcpi)]

  result_all = reg_data[, .(model = list(ivreg(lsold ~ lprice + labove_ref + lbelow_ref + lotherPrice + 
                                        lcpi + lunemploy + Christmas + Thanksgiving + Easter + 
                                        promotion | lhausman + IV2_above_ref + IV2_below_ref + lotherPrice + 
                                        lcpi + lunemploy + Christmas + Thanksgiving + Easter + promotion,
                                        na.action = na.exclude))),
                        by = .(chain_mkt, brand_descr_corrected)]
  result_0607 = reg_data[year %in% 2006:2007, 
                         .(model = list(ivreg(lsold ~ lprice + labove_ref + lbelow_ref + lotherPrice + 
                                        lcpi + lunemploy + Christmas + Thanksgiving + Easter + 
                                        promotion | lhausman + IV2_above_ref + IV2_below_ref + lotherPrice + 
                                        lcpi + lunemploy + Christmas + Thanksgiving + Easter + promotion,
                                        na.action = na.exclude))),
                        by = .(chain_mkt, brand_descr_corrected)]
  result_0810 = reg_data[yearmonth %in% 200806:201012, 
                         .(model = list(ivreg(lsold ~ lprice + labove_ref + lbelow_ref + lotherPrice + 
                                        lcpi + lunemploy + Christmas + Thanksgiving + Easter + 
                                        promotion | lhausman + IV2_above_ref + IV2_below_ref + lotherPrice + 
                                        lcpi + lunemploy + Christmas + Thanksgiving + Easter + promotion,
                                        na.action = na.exclude))),
                        by = .(chain_mkt, brand_descr_corrected)]  
  result_08 = reg_data[year %in% 2008, 
                         .(model = list(ivreg(lsold ~ lprice + labove_ref + lbelow_ref + lotherPrice + 
                                        lcpi + lunemploy + Christmas + Thanksgiving + Easter + 
                                        promotion | lhausman + IV2_above_ref + IV2_below_ref + lotherPrice + 
                                        lcpi + lunemploy + Christmas + Thanksgiving + Easter + promotion,
                                        na.action = na.exclude))),
                        by = .(chain_mkt, brand_descr_corrected)]
  
# coefficients and p-values
  result_all[, c("intercept", "coef_lprice", "coef_labove_ref", "coef_lbelow_ref", "coef_lotherPrice", 
               "coef_lcpi", "coef_lunemploy", "coef_Christmas", "coef_Thanksgiving", "coef_Easter", 
               "coef_promotion") := as.list(model[[1]]$coefficients),
             by = .(chain_mkt, brand_descr_corrected)]  
  result_all = na.omit(result_all)
  result_all[, c("pval_intercept", "pval_lprice", "pval_labove_ref", "pval_lbelow_ref", "pval_lotherPrice",
               "pval_lcpi", "pval_lunemploy", "pval_Christmas", "pval_Thanksgiving", "pval_Easter",
               "pval_promotion") := as.list(summary(model[[1]])$coefficients[,"Pr(>|t|)"]),
             by = .(chain_mkt, brand_descr_corrected)]
  
  result_0607[, c("intercept", "coef_lprice", "coef_labove_ref", "coef_lbelow_ref", "coef_lotherPrice", 
               "coef_lcpi", "coef_lunemploy", "coef_Christmas", "coef_Thanksgiving", "coef_Easter", 
               "coef_promotion") := as.list(model[[1]]$coefficients),
             by = .(chain_mkt, brand_descr_corrected)]
  result_0607 = na.omit(result_0607)
  result_0607[, c("pval_intercept", "pval_lprice", "pval_labove_ref", "pval_lbelow_ref", "pval_lotherPrice",
               "pval_lcpi", "pval_lunemploy", "pval_Christmas", "pval_Thanksgiving", "pval_Easter",
               "pval_promotion") := as.list(summary(model[[1]])$coefficients[,"Pr(>|t|)"]),
             by = .(chain_mkt, brand_descr_corrected)]
  
  result_0810[, c("intercept", "coef_lprice", "coef_labove_ref", "coef_lbelow_ref", "coef_lotherPrice", 
               "coef_lcpi", "coef_lunemploy", "coef_Christmas", "coef_Thanksgiving", "coef_Easter", 
               "coef_promotion") := as.list(model[[1]]$coefficients),
             by = .(chain_mkt, brand_descr_corrected)]
  result_0810 = na.omit(result_0810)
  result_0810[, c("pval_intercept", "pval_lprice", "pval_labove_ref", "pval_lbelow_ref", "pval_lotherPrice",
               "pval_lcpi", "pval_lunemploy", "pval_Christmas", "pval_Thanksgiving", "pval_Easter",
               "pval_promotion") := as.list(summary(model[[1]])$coefficients[,"Pr(>|t|)"]),
             by = .(chain_mkt, brand_descr_corrected)]
  
  result_08[, c("intercept", "coef_lprice", "coef_labove_ref", "coef_lbelow_ref", "coef_lotherPrice", 
               "coef_lcpi", "coef_lunemploy", "coef_Christmas", "coef_Thanksgiving", "coef_Easter", 
               "coef_promotion") := as.list(model[[1]]$coefficients),
             by = .(chain_mkt, brand_descr_corrected)]
  result_08 = na.omit(result_08)
  result_08[, c("pval_intercept", "pval_lprice", "pval_labove_ref", "pval_lbelow_ref", "pval_lotherPrice",
               "pval_lcpi", "pval_lunemploy", "pval_Christmas", "pval_Thanksgiving", "pval_Easter",
               "pval_promotion") := as.list(summary(model[[1]])$coefficients[,"Pr(>|t|)"]),
             by = .(chain_mkt, brand_descr_corrected)]
  
# Histograms    
  variables = c("lprice", "labove_ref", "lbelow_ref", "lotherPrice", "lcpi", "lunemploy", 
                "Christmas", "Thanksgiving", "Easter", "promotion")  
  resultBrand = unique(result_all$brand_descr_corrected)
  
  doHistogram(result_all, "All time")
  doHistogram(result_0607, "2006.01-2007.12")
  doHistogram(result_0810, "2008.06-2010.12")
  doHistogram(result_08, "2008")
```

```{r}
# 2.3 IV3
  reg_data = target_data[, .(year, yearmonth, week_end, lsold, lprice, lref, labove_ref, lbelow_ref,
                           lotherPrice, Christmas, Thanksgiving, Easter, promotion, 
                           brand_descr_corrected, chain_mkt, lhausman, lunemploy, lcpi)]

  result_all = reg_data
  result_all[, lprice_fitted := fitted(lm(lprice ~ lhausman + lref + lotherPrice + lcpi + lunemploy + 
                                           Christmas + Thanksgiving + Easter + promotion, na.action = na.exclude)), 
               by = .(chain_mkt, brand_descr_corrected)]
  
  result_all[, `:=`(labove_ref2 = lprice_fitted-lref, lbelow_ref2 = lprice_fitted-lref)]
  result_all[lref > lprice_fitted, labove_ref2 := 0]
  result_all[lref < lprice_fitted, lbelow_ref2 := 0]
  
  result_all = result_all[, .(model = list(lm(lsold ~ lprice_fitted + labove_ref2 + lbelow_ref2 + lotherPrice + 
                                               lcpi + lunemploy + Christmas + Thanksgiving + Easter + 
                                               promotion, na.action = na.exclude))),
                        by = .(chain_mkt, brand_descr_corrected)]

  
  result_0607 = reg_data[year %in% 2006:2007, ]
  result_0607[, lprice_fitted := fitted(lm(lprice ~ lhausman + lref + lotherPrice + lcpi + lunemploy + 
                                           Christmas + Thanksgiving + Easter + promotion, na.action = na.exclude)), 
               by = .(chain_mkt, brand_descr_corrected)]
  
  result_0607[, `:=`(labove_ref2 = lprice_fitted-lref, lbelow_ref2 = lprice_fitted-lref)]
  result_0607[lref > lprice_fitted, labove_ref2 := 0]
  result_0607[lref < lprice_fitted, lbelow_ref2 := 0]

  result_0607 = result_0607[, .(model = list(lm(lsold ~ lprice_fitted + labove_ref2 + lbelow_ref2 + lotherPrice + 
                                               lcpi + lunemploy + Christmas + Thanksgiving + Easter + 
                                               promotion, na.action = na.exclude))),
                            by = .(chain_mkt, brand_descr_corrected)]
  
  result_0810 = reg_data[yearmonth %in% 200806:201012, ]
  result_0810[, lprice_fitted := fitted(lm(lprice ~ lhausman + lref + lotherPrice + lcpi + lunemploy + 
                                           Christmas + Thanksgiving + Easter + promotion, na.action = na.exclude)), 
               by = .(chain_mkt, brand_descr_corrected)]
  
  result_0810[, `:=`(labove_ref2 = lprice_fitted-lref, lbelow_ref2 = lprice_fitted-lref)]
  result_0810[lref > lprice_fitted, labove_ref2 := 0]
  result_0810[lref < lprice_fitted, lbelow_ref2 := 0]

  result_0810 = result_0810[, .(model = list(lm(lsold ~ lprice_fitted + labove_ref2 + lbelow_ref2 + lotherPrice + 
                                               lcpi + lunemploy + Christmas + Thanksgiving + Easter + 
                                               promotion, na.action = na.exclude))),
                            by = .(chain_mkt, brand_descr_corrected)]
  
  result_08 = reg_data[year %in% 2008, ]
  result_08[, lprice_fitted := fitted(lm(lprice ~ lhausman + lref + lotherPrice + lcpi + lunemploy + 
                                           Christmas + Thanksgiving + Easter + promotion, na.action = na.exclude)), 
               by = .(chain_mkt, brand_descr_corrected)]
  
  result_08[, `:=`(labove_ref2 = lprice_fitted-lref, lbelow_ref2 = lprice_fitted-lref)]
  result_08[lref > lprice_fitted, labove_ref2 := 0]
  result_08[lref < lprice_fitted, lbelow_ref2 := 0]

  result_08 = result_08[, .(model = list(lm(lsold ~ lprice_fitted + labove_ref2 + lbelow_ref2 + lotherPrice + 
                                               lcpi + lunemploy + Christmas + Thanksgiving + Easter + 
                                               promotion, na.action = na.exclude))),
                            by = .(chain_mkt, brand_descr_corrected)]
  
  # coefficients and p-values
  result_all[, c("intercept", "coef_lprice_fitted", "coef_labove_ref2", "coef_lbelow_ref2", "coef_lotherPrice", 
               "coef_lcpi", "coef_lunemploy", "coef_Christmas", "coef_Thanksgiving", "coef_Easter", 
               "coef_promotion") := unlist(model)[which(grepl("coefficient",names(unlist(model))))],
             by = .(chain_mkt, brand_descr_corrected)]  
  result_all = na.omit(result_all)
  result_all[, c("pval_intercept", "pval_lprice_fitted", "pval_labove_ref2", "pval_lbelow_ref2", "pval_lotherPrice",
               "pval_lcpi", "pval_lunemploy", "pval_Christmas", "pval_Thanksgiving", "pval_Easter",
               "pval_promotion") := as.list(summary(model[[1]])$coefficients[,"Pr(>|t|)"]),
             by = .(chain_mkt, brand_descr_corrected)]
  
  result_0607[, c("intercept", "coef_lprice_fitted", "coef_labove_ref2", "coef_lbelow_ref2", "coef_lotherPrice", 
               "coef_lcpi", "coef_lunemploy", "coef_Christmas", "coef_Thanksgiving", "coef_Easter", 
               "coef_promotion") := unlist(model)[which(grepl("coefficient",names(unlist(model))))],
             by = .(chain_mkt, brand_descr_corrected)]
  result_0607 = na.omit(result_0607)
  result_0607[, c("pval_intercept", "pval_lprice_fitted", "pval_labove_ref2", "pval_lbelow_ref2", "pval_lotherPrice",
               "pval_lcpi", "pval_lunemploy", "pval_Christmas", "pval_Thanksgiving", "pval_Easter",
               "pval_promotion") := as.list(summary(model[[1]])$coefficients[,"Pr(>|t|)"]),
             by = .(chain_mkt, brand_descr_corrected)]
  
  result_0810[, c("intercept", "coef_lprice_fitted", "coef_labove_ref2", "coef_lbelow_ref2", "coef_lotherPrice", 
               "coef_lcpi", "coef_lunemploy", "coef_Christmas", "coef_Thanksgiving", "coef_Easter", 
               "coef_promotion") := unlist(model)[which(grepl("coefficient",names(unlist(model))))],
             by = .(chain_mkt, brand_descr_corrected)]
  result_0810 = na.omit(result_0810)
  result_0810[, c("pval_intercept", "pval_lprice_fitted", "pval_labove_ref2", "pval_lbelow_ref2", "pval_lotherPrice",
               "pval_lcpi", "pval_lunemploy", "pval_Christmas", "pval_Thanksgiving", "pval_Easter",
               "pval_promotion") := as.list(summary(model[[1]])$coefficients[,"Pr(>|t|)"]),
             by = .(chain_mkt, brand_descr_corrected)]
  
  result_08[, c("intercept", "coef_lprice_fitted", "coef_labove_ref2", "coef_lbelow_ref2", "coef_lotherPrice", 
               "coef_lcpi", "coef_lunemploy", "coef_Christmas", "coef_Thanksgiving", "coef_Easter", 
               "coef_promotion") := unlist(model)[which(grepl("coefficient",names(unlist(model))))],
             by = .(chain_mkt, brand_descr_corrected)]
  result_08 = na.omit(result_08)
  result_08[, c("pval_intercept", "pval_lprice_fitted", "pval_labove_ref2", "pval_lbelow_ref2", "pval_lotherPrice",
               "pval_lcpi", "pval_lunemploy", "pval_Christmas", "pval_Thanksgiving", "pval_Easter",
               "pval_promotion") := as.list(summary(model[[1]])$coefficients[,"Pr(>|t|)"]),
             by = .(chain_mkt, brand_descr_corrected)]
   
# Histograms    
  variables = c("lprice_fitted", "labove_ref2", "lbelow_ref2", "lotherPrice", "lcpi", "lunemploy", 
                "Christmas", "Thanksgiving", "Easter", "promotion")
  resultBrand = unique(result_all$brand_descr_corrected)
  
  doHistogram(result_all, "All time")
  doHistogram(result_0607, "2006.01-2007.12")
  doHistogram(result_0810, "2008.06-2010.12")
  doHistogram(result_08, "2008")
```
  

  
  
  
  
  
  
  